### PR TITLE
canInteract and canUse

### LINKED ISSUE #4: [Suggestion] canInteract
Hi, this lib is awesome!

Maybe you'd also like to add a canInteract thing, e.g. whether players are allowed to open a chest, etc.

### PR DESCRIPTION
**Pull request by Boy0000**
Closes #4 

Not tested at all and unsure if it makes fully sense. FactionsUUID uses LEVER permcheck as there is no "interact". ITEM is also not really using an item so probably needs to be changed

### CODE REVIEW

**Comment by Boy0000** [comment]
@Th0rgal mind taking a look at this?

**Comment by KaspianDev** [comment]
@Th0rgal :P

**Comment by Th0rgal** [comment]
Should I still merge it?

**Comment by Boy0000** [comment]
Nah probably needs to be redone, ill get to it eventually

**Pull request closed without merging**
