### PR TITLE
Add BentoBox compatibility.

### PR DESCRIPTION
**Pull request by tastybento**
This adds support for BentoBox (https://bentobox.world). An admin wanted Oraxen items to be protected on the islands.

It would also be useful if Oraxen could fire Bukkit events, like PlaceBlockEvent because that's what the BentoBox protection natively triggers off, but that's not in this PR.

I could not get my IDE to build using the Gradle setup as-is and I'm a Maven guy, bot Gradle so after two days I gave up and just wrote the code as-is. I think it should work, but it's not tested. If you see an issue, please let me know and I'll try and fix it. FWIW, I'm using Eclipse...

Thanks!

### CODE REVIEW

**Comment by tastybento** [comment]
I got Gradle working and this now compiles correctly.

**Comment by tastybento** [comment]
Is this okay to merge?

**Comment by tastybento** [comment]
@Real6dq I fixed the merge conflicts in the gradle file. Should be good to merge.

**Comment by Boy0000** [comment]
> This adds support for BentoBox (https://bentobox.world). An admin wanted Oraxen items to be protected on the islands.
> 
> It would also be useful if Oraxen could fire Bukkit events, like PlaceBlockEvent because that's what the BentoBox protection natively triggers off, but that's not in this PR.
> 
> I could not get my IDE to build using the Gradle setup as-is and I'm a Maven guy, bot Gradle so after two days I gave up and just wrote the code as-is. I think it should work, but it's not tested. If you see an issue, please let me know and I'll try and fix it. FWIW, I'm using Eclipse...
> 
> Thanks!

Sorry for not seeing this! For some reason not getting notifications from this repo
Oraxen fires its own events, as well as BlockPlaceEvent etc, for breaking and placing blocks/furniture
You can also listen to Oraxens relevant events.

Either way this looks good ill merge it soonTM thank you

**Comment by Boy0000** [comment]
@tastybento Also realised the BentoBoxCompatibility is never initialized in the [CompatibilityManager](https://github.com/oraxen/protectionlib/blob/master/src/main/java/io/th0rgal/protectionlib/ProtectionLib.java)

**Comment by tastybento** [comment]
Okay, these have been updated.

**Comment by Boy0000** [comment]
Thank you for the PR 👍

**Pull request merged**
